# Generated by Django 3.0.3 on 2023-12-04 20:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Albums',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('album_name', models.CharField(max_length=256)),
                ('release', models.DateField(blank=True)),
                ('cover', models.URLField()),
                ('popularity', models.IntegerField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Songs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('song_id', models.CharField(db_index=True, max_length=256)),
                ('name', models.CharField(max_length=256)),
                ('danceability', models.FloatField(blank=True)),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='musicdata.Albums')),
            ],
        ),
    ]
